// packages/core/src/components/Input/Input.styles.ts
/// Zero-dependency input styles using pure SASS-generated classes
/// @fileoverview Input styling without external dependencies

import { cva, type VariantProps } from "../../utils/cn";

/**
 * Input variants using pure SASS-generated classes
 * These classes are generated by our SASS build system
 */
export const inputVariants = cva(
  // Base classes - generated by SASS
  "mild-input",
  {
    variants: {
      variant: {
        outline: "mild-input--outline",
        filled: "mild-input--filled",
        flushed: "mild-input--flushed",
        unstyled: "mild-input--unstyled",
      },
      size: {
        sm: "mild-input--sm",
        md: "mild-input--md",
        lg: "mild-input--lg",
      },
      fullWidth: {
        true: "mild-input--full-width",
        false: "",
      },
      error: {
        true: "mild-input--error",
        false: "",
      },
      disabled: {
        true: "mild-input--disabled",
        false: "",
      },
      readonly: {
        true: "mild-input--readonly",
        false: "",
      },
      required: {
        true: "mild-input--required",
        false: "",
      },
    },
    compoundVariants: [
      // Error state overrides for different variants
      {
        variant: "outline",
        error: true,
        class: "mild-input--outline-error",
      },
      {
        variant: "filled",
        error: true,
        class: "mild-input--filled-error",
      },
      {
        variant: "flushed",
        error: true,
        class: "mild-input--flushed-error",
      },
      // Disabled state overrides
      {
        variant: "filled",
        disabled: true,
        class: "mild-input--filled-disabled",
      },
    ],
    defaultVariants: {
      variant: "outline",
      size: "md",
      fullWidth: true,
      error: false,
      disabled: false,
      readonly: false,
      required: false,
    },
  },
);

export type InputVariantProps = VariantProps<typeof inputVariants>;

/**
 * Input group variants for input with addons
 */
export const inputGroupVariants = cva("mild-input-group", {
  variants: {
    size: {
      sm: "mild-input-group--sm",
      md: "mild-input-group--md",
      lg: "mild-input-group--lg",
    },
    error: {
      true: "mild-input-group--error",
      false: "",
    },
  },
  defaultVariants: {
    size: "md",
    error: false,
  },
});

/**
 * Input addon variants (left/right elements)
 */
export const inputAddonVariants = cva("mild-input-addon", {
  variants: {
    position: {
      left: "mild-input-addon--left",
      right: "mild-input-addon--right",
    },
    size: {
      sm: "mild-input-addon--sm",
      md: "mild-input-addon--md",
      lg: "mild-input-addon--lg",
    },
  },
  defaultVariants: {
    size: "md",
  },
});
