// packages/core/src/components/InputPassword/InputPassword.styles.ts
import { cva, VariantProps } from "../../utils/cn";

export const inputPasswordVariants = cva(
  // Base classes - generated by SASS
  "mild-input-password",
  {
    variants: {
      variant: {
        outline: "mild-input-password--outline",
        filled: "mild-input-password--filled",
        flushed: "mild-input-password--flushed",
        unstyled: "mild-input-password--unstyled",
      },
      size: {
        sm: "mild-input-password--sm",
        md: "mild-input-password--md",
        lg: "mild-input-password--lg",
      },
      fullWidth: {
        true: "mild-input-password--full-width",
        false: "",
      },
      error: {
        true: "mild-input-password--error",
        false: "",
      },
      disabled: {
        true: "mild-input-password--disabled",
        false: "",
      },
      readonly: {
        true: "mild-input-password--readonly",
        false: "",
      },
      required: {
        true: "mild-input-password--required",
        false: "",
      },
    },
    compoundVariants: [
      // Error state overrides for different variants
      {
        variant: "outline",
        error: true,
        class: "mild-input-password--outline-error",
      },
      {
        variant: "filled",
        error: true,
        class: "mild-input-password--filled-error",
      },
      {
        variant: "flushed",
        error: true,
        class: "mild-input-password--flushed-error",
      },
      // Disabled state overrides
      {
        variant: "filled",
        disabled: true,
        class: "mild-input-password--filled-disabled",
      },
    ],
    defaultVariants: {
      variant: "outline",
      size: "md",
      fullWidth: true,
      error: false,
      disabled: false,
      readonly: false,
      required: false,
    },
  },
);

export type InputPasswordVariantProps = VariantProps<
  typeof inputPasswordVariants
>;

export const inputPasswordToggleVariants = cva("mild-input-password--toggle", {
  variants: {
    size: {
      sm: "mild-input-password--toggle-sm",
      md: "mild-input-password--toggle-md",
      lg: "mild-input-password--toggle-lg",
    },
  },
  defaultVariants: {
    size: "md",
  },
});
