# .github/workflows/deploy-storybooks.yml

name: Build and Deploy Multi-Framework Storybooks
on:
  push:
    branches: [main]
    paths:
      - "packages/core/**"
      - "packages/react/**"
      - "packages/vue/**"
      - "storybook/react/**"
      - "storybook/vue/**"
      - ".github/workflows/storybook.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build core package
        run: pnpm --filter @mild-ui/core build

      - name: Build React package
        run: pnpm --filter @mild-ui/react build

      - name: Build Vue package
        run: pnpm --filter @mild-ui/vue build

      - name: Build React Storybook
        run: |
          cd storybook/react
          STORYBOOK_BASE_URL="/mild-ui/react/" pnpm build
        env:
          NODE_ENV: production

      - name: Build Vue Storybook
        run: |
          cd storybook/vue
          STORYBOOK_BASE_URL="/mild-ui/vue/" pnpm build
        env:
          NODE_ENV: production

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          mkdir -p deploy/react
          mkdir -p deploy/vue

      - name: Copy React Storybook
        run: cp -r storybook/react/storybook-static/* deploy/react/

      - name: Copy Vue Storybook
        run: cp -r storybook/vue/storybook-static/* deploy/vue/

      - name: Create main index page
        run: |
          cat > deploy/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>mild-ui Component Library</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
                      max-width: 800px;
                      margin: 0 auto;
                      padding: 2rem;
                      background: #fafafa;
                  }
                  .container {
                      background: white;
                      padding: 3rem;
                      border-radius: 8px;
                      box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
                  }
                  h1 {
                      color: #1f2937;
                      border-bottom: 2px solid #3b82f6;
                      padding-bottom: 1rem;
                  }
                  .frameworks {
                      display: grid;
                      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                      gap: 1.5rem;
                      margin-top: 2rem;
                  }
                  .framework-card {
                      border: 1px solid #e5e7eb;
                      border-radius: 8px;
                      padding: 1.5rem;
                      text-align: center;
                      transition: transform 0.2s, box-shadow 0.2s;
                  }
                  .framework-card:hover {
                      transform: translateY(-2px);
                      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
                  }
                  .framework-card h3 {
                      margin: 0 0 1rem 0;
                      color: #374151;
                  }
                  .framework-card a {
                      display: inline-block;
                      background: #3b82f6;
                      color: white;
                      padding: 0.75rem 1.5rem;
                      text-decoration: none;
                      border-radius: 6px;
                      font-weight: 500;
                      transition: background 0.2s;
                  }
                  .framework-card a:hover {
                      background: #2563eb;
                  }
                  .description {
                      color: #6b7280;
                      line-height: 1.6;
                      margin-bottom: 2rem;
                  }
                  .badge {
                      display: inline-block;
                      background: #10b981;
                      color: white;
                      padding: 0.25rem 0.75rem;
                      border-radius: 9999px;
                      font-size: 0.875rem;
                      font-weight: 500;
                      margin-left: 0.5rem;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>mild-ui Component Library <span class="badge">Multi-Framework</span></h1>
                  
                  <p class="description">
                      Welcome to mild-ui, a cross-framework UI component library inspired by shadcn/ui. 
                      Our components work seamlessly across React, Vue, and Svelte, providing a consistent 
                      design system for all your projects.
                  </p>
          
                  <div class="frameworks">
                      <div class="framework-card">
                          <h3>⚛️ React</h3>
                          <p>Explore React components with Radix UI primitives</p>
                          <a href="./react/">View React Storybook</a>
                      </div>
                      
                      <div class="framework-card">
                          <h3>💚 Vue</h3>
                          <p>Discover Vue 3 components with Composition API</p>
                          <a href="./vue/">View Vue Storybook</a>
                      </div>
                  </div>
                  
                  <div style="margin-top: 3rem; text-align: center; color: #6b7280;">
                      <p>
                          <a href="https://github.com/CodeWithRiyan/mild-ui" style="color: #3b82f6; text-decoration: none;">
                              📚 Documentation & Source Code
                          </a>
                      </p>
                  </div>
              </div>
          </body>
          </html>
          EOF

      - name: Add .nojekyll file
        run: touch deploy/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          publish_branch: gh-pages
          force_orphan: true