name: Build and Deploy React Storybook
on:
  push:
    branches: [main]
    paths:
      - "packages/**"
      - "storybook/react/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: |
          pnpm --filter @mild-ui/core build
          pnpm --filter @mild-ui/react build

      - name: Build React Storybook for GitHub Pages
        run: |
          cd storybook/react
          NODE_ENV=production GITHUB_ACTIONS=true pnpm build
        env:
          NODE_ENV: production
          GITHUB_ACTIONS: true

      - name: Add .nojekyll file
        run: touch storybook/react/storybook-static/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook/react/storybook-static
          branch: gh-pages
