name: Build and Deploy Vue Storybook
on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**'
      - 'storybook/vue/**'
  workflow_dispatch: # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: |
          pnpm --filter @mild-ui/core build
          pnpm --filter @mild-ui/vue build
      
      - name: Build Vue Storybook for GitHub Pages
        run: |
          cd storybook/vue
          NODE_ENV=production GITHUB_ACTIONS=true pnpm build
        env:
          NODE_ENV: production
          GITHUB_ACTIONS: true
      
      - name: Add .nojekyll file
        run: touch storybook/vue/storybook-static/.nojekyll
      
      - name: Deploy to GitHub Pages (Vue subdirectory)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook/vue/storybook-static
          target-folder: vue
          branch: gh-pages