name: Build and Deploy React Storybook
on:
  push:
    branches: [main]
    paths:
      - "packages/core/**"
      - "packages/react/**"
      - "storybook/react/**"
      - ".github/workflows/storybook-react.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-react"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages-react
      url: ${{ steps.deployment.outputs.page_url }}react/
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: |
          pnpm --filter @mild-ui/core build
          pnpm --filter @mild-ui/react build

      - name: Build React Storybook
        run: |
          cd storybook/react
          NODE_ENV=production GITHUB_ACTIONS=true pnpm build
        env:
          NODE_ENV: production
          GITHUB_ACTIONS: true

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload React Storybook artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "./storybook/react/storybook-static"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
