name: Build and Deploy Storybooks
on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**'
      - 'storybook/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: |
          pnpm --filter @mild-ui/core build
          pnpm --filter @mild-ui/react build
          pnpm --filter @mild-ui/vue build
          pnpm --filter @mild-ui/svelte build
      
      - name: Build React Storybook
        run: |
          cd storybook/react
          # Set NODE_ENV and build with correct base path
          NODE_ENV=production npx storybook build --output-dir ../../public
        env:
          NODE_ENV: production
      
      - name: Create landing page
        run: |
          cat > public/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>mild-ui Component Library</title>
            <style>
              * {
                margin: 0;
                padding: 0;
                box-sizing: border-box;
              }
              
              body { 
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif;
                line-height: 1.6;
                color: #333;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                min-height: 100vh;
                display: flex;
                align-items: center;
                justify-content: center;
              }
              
              .container {
                max-width: 800px;
                margin: 0 auto;
                padding: 40px 20px;
                background: white;
                border-radius: 20px;
                box-shadow: 0 20px 40px rgba(0,0,0,0.1);
              }
              
              h1 {
                text-align: center;
                margin-bottom: 10px;
                color: #2d3748;
                font-size: 2.5rem;
                font-weight: 700;
              }
              
              .subtitle {
                text-align: center;
                margin-bottom: 40px;
                color: #718096;
                font-size: 1.1rem;
              }
              
              .framework { 
                margin: 30px 0; 
                padding: 30px; 
                border: 2px solid #e2e8f0; 
                border-radius: 15px; 
                background: #f7fafc;
                transition: all 0.3s ease;
              }
              
              .framework:hover {
                border-color: #3182ce;
                box-shadow: 0 10px 25px rgba(49, 130, 206, 0.1);
                transform: translateY(-2px);
              }
              
              .framework h2 { 
                margin-bottom: 15px;
                color: #2d3748;
                font-size: 1.5rem;
                display: flex;
                align-items: center;
                gap: 10px;
              }
              
              .framework p {
                margin-bottom: 20px;
                color: #4a5568;
              }
              
              .framework a { 
                display: inline-block; 
                padding: 12px 24px; 
                background: linear-gradient(135deg, #3182ce, #2c5282); 
                color: white; 
                text-decoration: none; 
                border-radius: 8px;
                font-weight: 600;
                transition: all 0.3s ease;
                box-shadow: 0 4px 15px rgba(49, 130, 206, 0.4);
              }
              
              .framework a:hover {
                transform: translateY(-2px);
                box-shadow: 0 8px 25px rgba(49, 130, 206, 0.6);
              }
              
              .status {
                display: inline-block;
                padding: 4px 12px;
                border-radius: 20px;
                font-size: 0.8rem;
                font-weight: 600;
                margin-left: 10px;
              }
              
              .available {
                background: #c6f6d5;
                color: #22543d;
              }
              
              .coming-soon {
                background: #fed7d7;
                color: #742a2a;
              }
              
              .footer {
                text-align: center;
                margin-top: 40px;
                padding-top: 30px;
                border-top: 1px solid #e2e8f0;
                color: #718096;
              }
              
              .footer a {
                color: #3182ce;
                text-decoration: none;
              }
              
              .footer a:hover {
                text-decoration: underline;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>🎨 mild-ui</h1>
              <p class="subtitle">Cross-framework UI components for React, Vue, and Svelte</p>
              
              <div class="framework">
                <h2>
                  ⚛️ React Components
                  <span class="status available">Available</span>
                </h2>
                <p>Explore our React component library with interactive examples and documentation.</p>
                <a href="./index.html">View React Storybook</a>
              </div>
              
              <div class="framework">
                <h2>
                  💚 Vue Components
                  <span class="status coming-soon">Coming Soon</span>
                </h2>
                <p>Vue implementation of mild-ui components (in development).</p>
              </div>
              
              <div class="framework">
                <h2>
                  🟠 Svelte Components
                  <span class="status coming-soon">Coming Soon</span>
                </h2>
                <p>Svelte implementation of mild-ui components (in development).</p>
              </div>
              
              <div class="footer">
                <p>Built with ❤️ by the mild-ui team</p>
                <p><a href="https://github.com/codewithriyan/mild-ui" target="_blank">View on GitHub</a></p>
              </div>
            </div>
          </body>
          </html>
          EOF
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages