name: Test
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [react, vue]

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build core package (CSS only)
        run: pnpm --filter @mild-ui/core build

      - name: Build and test ${{ matrix.framework }}
        run: |
          pnpm --filter @mild-ui/${{ matrix.framework }} build
          
          # Run tests if test files exist (excluding node_modules)
          if find packages/${{ matrix.framework }}/src -name "*.test.*" -o -name "*.spec.*" 2>/dev/null | grep -q .; then
            echo "Test files found, running tests..."
            pnpm --filter @mild-ui/${{ matrix.framework }} test
          else
            echo "No test files found in src/, skipping tests for ${{ matrix.framework }}"
          fi
